channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.10
  - conda-forge::pip
  - conda-forge::setuptools
  - conda-forge::ipykernel
  - conda-forge::tqdm
  - conda-forge::seaborn
  - pip:
      # source packages
      - "-e pydfds/"
      - "-e datamux/"
      - "-e curator/"
      - "-e plugins/streaminghub_codec_avro"
      - "-e plugins/streaminghub_codec_json"
      - "-e plugins/streaminghub_codec_msgpack"
      - "-e plugins/streaminghub_proxy_empatica_e4"
      - "-e plugins/streaminghub_proxy_lsl"
      - "-e plugins/streaminghub_proxy_pupil_core"
      - "-e plugins/streaminghub_rpc_websocket"
